# Generated by Django 5.2.3 on 2025-07-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_score_delete_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='score_value',
        ),
        migrations.RemoveField(
            model_name='score',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='score',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
