# Generated by Django 5.2.3 on 2025-07-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='votes',
            new_name='count',
        ),
    ]
