# Generated by Django 5.2.3 on 2025-07-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_votes_score_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('question', 'score_value')},
        ),
    ]
